### ISSUE TITLE
running `bundle install` can yield files with 600 permissions instead of 644

### ISSUE THREAD

**Issue by dmalan** [cs50/cli#58]
1. `cd ~`
1. `git clone git@github.com:cs50/cli.git`
1. `git checkout github-pages`
1. `make build`
1. `cd ~`
1. `git clone https://github.com/cs50/ap`
1. `cd ap`
1. `cli50 -f # note the -f, to ensure you use your local build of cs50/cli`
1. `bundle install`
1. `bundle exec jekyll build # yields error below`
1. `ls -l /var/lib/gems/2.5.0/specifications`

Cf. https://github.com/bundler/bundler/issues/2136, but hasn't yielded solution, despite https://github.com/cs50/cli/blob/github-pages/Dockerfile#L79-L80.

However, running `umask 0022` before `bundle install` does fix. Exit CS50 CLI then re-start with `cli50 -f` step above to try again.

```
$ bundle exec jekyll build
bundler: failed to load command: jekyll (/usr/local/bin/jekyll)
Errno::EACCES: Permission denied @ rb_sysopen - /var/lib/gems/2.5.0/specifications/minitest-5.11.3.gemspec
  /usr/lib/ruby/2.5.0/rubygems/stub_specification.rb:118:in `initialize'
  /usr/lib/ruby/2.5.0/rubygems/stub_specification.rb:118:in `open'
  /usr/lib/ruby/2.5.0/rubygems/stub_specification.rb:118:in `data'
  /usr/lib/ruby/2.5.0/rubygems/stub_specification.rb:208:in `valid?'
  /usr/lib/ruby/2.5.0/rubygems/specification.rb:768:in `select'
  /usr/lib/ruby/2.5.0/rubygems/specification.rb:768:in `gemspec_stubs_in'
  /usr/lib/ruby/2.5.0/rubygems/specification.rb:793:in `block in map_stubs'
  /usr/lib/ruby/2.5.0/rubygems/specification.rb:790:in `each'
  /usr/lib/ruby/2.5.0/rubygems/specification.rb:790:in `flat_map'
  /usr/lib/ruby/2.5.0/rubygems/specification.rb:790:in `map_stubs'
  /usr/lib/ruby/2.5.0/rubygems/specification.rb:782:in `installed_stubs'
  /usr/lib/ruby/2.5.0/rubygems/specification.rb:850:in `stubs'
  /var/lib/gems/2.5.0/gems/bundler-1.16.4/lib/bundler/rubygems_integration.rb:817:in `all_specs'
  /var/lib/gems/2.5.0/gems/bundler-1.16.4/lib/bundler/source/rubygems.rb:350:in `block in installed_specs'
  /var/lib/gems/2.5.0/gems/bundler-1.16.4/lib/bundler/index.rb:11:in `build'
  /var/lib/gems/2.5.0/gems/bundler-1.16.4/lib/bundler/source/rubygems.rb:349:in `installed_specs'
  /var/lib/gems/2.5.0/gems/bundler-1.16.4/lib/bundler/source/rubygems.rb:91:in `specs'
  /var/lib/gems/2.5.0/gems/bundler-1.16.4/lib/bundler/lazy_specification.rb:76:in `__materialize__'
  /var/lib/gems/2.5.0/gems/bundler-1.16.4/lib/bundler/spec_set.rb:88:in `block in materialize'
  /var/lib/gems/2.5.0/gems/bundler-1.16.4/lib/bundler/spec_set.rb:85:in `map!'
  /var/lib/gems/2.5.0/gems/bundler-1.16.4/lib/bundler/spec_set.rb:85:in `materialize'
  /var/lib/gems/2.5.0/gems/bundler-1.16.4/lib/bundler/definition.rb:171:in `specs'
  /var/lib/gems/2.5.0/gems/bundler-1.16.4/lib/bundler/definition.rb:238:in `specs_for'
  /var/lib/gems/2.5.0/gems/bundler-1.16.4/lib/bundler/definition.rb:227:in `requested_specs'
  /var/lib/gems/2.5.0/gems/bundler-1.16.4/lib/bundler/runtime.rb:108:in `block in definition_method'
  /var/lib/gems/2.5.0/gems/bundler-1.16.4/lib/bundler/runtime.rb:20:in `setup'
  /var/lib/gems/2.5.0/gems/bundler-1.16.4/lib/bundler.rb:107:in `setup'
  /var/lib/gems/2.5.0/gems/bundler-1.16.4/lib/bundler/setup.rb:10:in `<top (required)>'
  /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
  /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
```

```
$ ls -l /var/lib/gems/2.5.0/specifications
total 432
-rw-r--r-- 1 root root  1965 Sep  2 00:37 activesupport-4.2.10.gemspec
-rw-r--r-- 1 root root  1656 Sep  2 00:36 addressable-2.5.2.gemspec
-rw-r--r-- 1 root root  1273 Sep  2 00:35 arr-pm-0.0.10.gemspec
-rw-r--r-- 1 root root  4073 Sep  2 00:35 asciidoctor-1.5.7.1.gemspec
-rw-r--r-- 1 root root   820 Sep  2 00:35 backports-3.11.4.gemspec
-rw-r--r-- 1 root root  2877 Sep  2 00:35 bundler-1.16.4.gemspec
-rw-r--r-- 1 root root  1360 Sep  2 00:35 cabin-0.9.0.gemspec
-rw-r--r-- 1 root root  2057 Sep  2 00:36 childprocess-0.9.0.gemspec
-rw-r--r-- 1 root root   820 Sep  2 00:35 clamp-1.0.1.gemspec
-rw-r--r-- 1 root root  1678 Sep  2 00:37 coffee-script-2.4.1.gemspec
-rw-r--r-- 1 root root  1044 Sep  2 00:37 coffee-script-source-1.11.1.gemspec
-rw-r--r-- 1 root root  1244 Sep  2 00:36 colorator-1.1.0.gemspec
-rw-r--r-- 1 root root  2601 Sep  2 00:36 commonmarker-0.17.11.gemspec
-rw-r--r-- 1 root root  1293 Sep  2 00:36 concurrent-ruby-1.0.5.gemspec
-rw-r--r-- 1 root root  3117 Sep  2 00:36 dnsruby-1.61.2.gemspec
-rw-r--r-- 1 root root  1492 Sep  2 00:36 dotenv-2.5.0.gemspec
-rw-r--r-- 1 root root  1378 Sep  2 00:36 em-websocket-0.5.1.gemspec
-rw-r--r-- 1 root root  1042 Sep  2 00:37 ethon-0.11.0.gemspec
-rw-r--r-- 1 root root  3599 Sep  2 00:36 eventmachine-1.2.7.gemspec
-rw-r--r-- 1 root root  1183 Sep  2 00:37 execjs-2.7.0.gemspec
-rw-r--r-- 1 root root  1117 Sep  2 00:37 faraday-0.15.2.gemspec
-rw-r--r-- 1 root root  2099 Sep  2 00:36 ffi-1.9.25.gemspec
-rw-r--r-- 1 root root   804 Sep  2 00:36 forwardable-extended-2.6.0.gemspec
-rw-r--r-- 1 root root  3623 Sep  2 00:36 fpm-1.10.2.gemspec
-rw-r--r-- 1 root root   850 Sep  2 00:37 gemoji-3.0.0.gemspec
-rw-r--r-- 1 root root 10975 Sep  2 00:37 github-pages-191.gemspec
-rw-r--r-- 1 root root  3025 Sep  2 00:37 github-pages-health-check-1.8.1.gemspec
-rw-r--r-- 1 root root  1671 Sep  2 00:37 html-pipeline-2.8.4.gemspec
-rw-r--r-- 1 root root  2290 Sep  2 00:36 http_parser.rb-0.6.0.gemspec
-rw-r--r-- 1 root root  1346 Sep  2 00:36 i18n-0.9.5.gemspec
-rw-r--r-- 1 root root   774 Sep  2 00:36 insist-1.0.0.gemspec
-rw-r--r-- 1 root root  2081 Sep  2 00:36 io-like-0.3.0.gemspec
-rw-r--r-- 1 root root  3421 Sep  2 00:36 jekyll-3.7.3.gemspec
-rw-r--r-- 1 root root  3421 Sep  2 00:39 jekyll-3.8.3.gemspec
-rw-r--r-- 1 root root  1850 Sep  2 00:39 jekyll-asciidoc-2.1.0.gemspec
-rw-r--r-- 1 root root  1972 Sep  2 00:37 jekyll-avatar-0.6.0.gemspec
-rw-r--r-- 1 root root  2133 Sep  2 00:37 jekyll-coffeescript-1.1.1.gemspec
-rw-r--r-- 1 root root  1943 Sep  2 00:36 jekyll-commonmark-1.2.0.gemspec
-rw-r--r-- 1 root root  1939 Sep  2 00:36 jekyll-commonmark-ghpages-0.1.5.gemspec
-rw-r--r-- 1 root root  1420 Sep  2 00:37 jekyll-default-layout-0.1.4.gemspec
-rw-r--r-- 1 root root  2121 Sep  2 00:37 jekyll-feed-0.10.0.gemspec
-rw-r--r-- 1 root root  2126 Sep  2 00:37 jekyll-gist-1.5.0.gemspec
-rw-r--r-- 1 root root  2081 Sep  2 00:37 jekyll-github-metadata-2.9.4.gemspec
-rw-r--r-- 1 root root  1809 Sep  2 00:37 jekyll-mentions-1.4.1.gemspec
-rw-r--r-- 1 root root  1449 Sep  2 00:37 jekyll-optional-front-matter-0.3.0.gemspec
-rw-r--r-- 1 root root  1545 Sep  2 00:37 jekyll-paginate-1.1.0.gemspec
-rw-r--r-- 1 root root  1423 Sep  2 00:37 jekyll-readme-index-0.2.0.gemspec
-rw-r--r-- 1 root root  1973 Sep  2 00:37 jekyll-redirect-from-0.14.0.gemspec
-rw-r--r-- 1 root root  1454 Sep  2 00:37 jekyll-relative-links-0.5.3.gemspec
-rw-r--r-- 1 root root  2456 Sep  2 00:37 jekyll-remote-theme-0.3.1.gemspec
-rw-r--r-- 1 root root  1888 Sep  2 00:36 jekyll-sass-converter-1.5.2.gemspec
-rw-r--r-- 1 root root  2028 Sep  2 00:37 jekyll-seo-tag-2.5.0.gemspec
-rw-r--r-- 1 root root  1956 Sep  2 00:37 jekyll-sitemap-1.2.0.gemspec
-rw-r--r-- 1 root root  1391 Sep  2 00:37 jekyll-swiss-0.4.0.gemspec
-rw-r--r-- 1 root root  1860 Sep  2 00:37 jekyll-theme-architect-0.1.1.gemspec
-rw-r--r-- 1 root root  1845 Sep  2 00:37 jekyll-theme-cayman-0.1.1.gemspec
-rw-r--r-- 1 root root  1843 Sep  2 00:37 jekyll-theme-dinky-0.1.1.gemspec
-rw-r--r-- 1 root root  1849 Sep  2 00:37 jekyll-theme-hacker-0.1.1.gemspec
-rw-r--r-- 1 root root  1856 Sep  2 00:37 jekyll-theme-leap-day-0.1.1.gemspec
-rw-r--r-- 1 root root  1849 Sep  2 00:37 jekyll-theme-merlot-0.1.1.gemspec
-rw-r--r-- 1 root root  1856 Sep  2 00:37 jekyll-theme-midnight-0.1.1.gemspec
-rw-r--r-- 1 root root  1851 Sep  2 00:37 jekyll-theme-minimal-0.1.1.gemspec
-rw-r--r-- 1 root root  1861 Sep  2 00:37 jekyll-theme-modernist-0.1.1.gemspec
-rw-r--r-- 1 root root  2062 Sep  2 00:37 jekyll-theme-primer-0.5.3.gemspec
-rw-r--r-- 1 root root  1844 Sep  2 00:37 jekyll-theme-slate-0.1.1.gemspec
-rw-r--r-- 1 root root  1850 Sep  2 00:37 jekyll-theme-tactile-0.1.1.gemspec
-rw-r--r-- 1 root root  1874 Sep  2 00:37 jekyll-theme-time-machine-0.1.1.gemspec
-rw-r--r-- 1 root root  1476 Sep  2 00:37 jekyll-titles-from-headings-0.5.1.gemspec
-rw-r--r-- 1 root root  1984 Sep  2 00:36 jekyll-watch-2.0.0.gemspec
-rw-r--r-- 1 root root  1972 Sep  2 00:37 jemoji-0.10.1.gemspec
-rw-r--r-- 1 root root  1769 Sep  2 00:35 json-1.8.6.gemspec
-rw-r--r-- 1 root root  3186 Sep  2 00:36 kramdown-1.17.0.gemspec
-rw-r--r-- 1 root root  1400 Sep  2 00:36 liquid-4.0.0.gemspec
-rw-r--r-- 1 root root  1904 Sep  2 00:36 listen-3.1.5.gemspec
-rw-r--r-- 1 root root  1540 Sep  2 00:36 mercenary-0.3.6.gemspec
-rw-r--r-- 1 root root  1632 Sep  2 00:37 minima-2.5.0.gemspec
-rw-r--r-- 1 root root  2247 Sep  2 00:37 mini_portile2-2.3.0.gemspec
-rw------- 1 root root  4804 Sep  2 01:25 minitest-5.11.3.gemspec
-rw-r--r-- 1 root root  2704 Sep  2 00:39 multi_json-1.13.1.gemspec
-rw-r--r-- 1 root root  1020 Sep  2 00:36 multipart-post-2.0.0.gemspec
-rw-r--r-- 1 root root  2388 Sep  2 00:36 mustache-0.99.8.gemspec
-rw-r--r-- 1 root root  7635 Sep  2 00:37 nokogiri-1.8.4.gemspec
-rw-r--r-- 1 root root  1491 Sep  2 00:37 octokit-4.11.0.gemspec
-rw-r--r-- 1 root root  1141 Sep  2 00:36 pathutil-0.16.1.gemspec
-rw-r--r-- 1 root root  2004 Sep  2 00:36 pleaserun-0.0.30.gemspec
-rw-r--r-- 1 root root  1638 Sep  2 00:36 public_suffix-2.0.5.gemspec
-rw-r--r-- 1 root root  1510 Sep  2 00:39 pygments.rb-1.2.1.gemspec
-rw-r--r-- 1 root root  1802 Sep  2 00:36 rb-fsevent-0.10.3.gemspec
-rw-r--r-- 1 root root  1661 Sep  2 00:36 rb-inotify-0.9.10.gemspec
-rw-r--r-- 1 root root   885 Sep  2 00:36 rouge-2.2.1.gemspec
-rw-r--r-- 1 root root  1254 Sep  2 00:36 ruby_dep-1.5.0.gemspec
-rw-r--r-- 1 root root   999 Sep  2 00:36 ruby-enum-0.7.2.gemspec
-rw-r--r-- 1 root root  2062 Sep  2 00:36 ruby-xz-0.2.3.gemspec
-rw-r--r-- 1 root root  1818 Sep  2 00:37 rubyzip-1.2.2.gemspec
-rw-r--r-- 1 root root   924 Sep  2 00:36 safe_yaml-1.0.4.gemspec
-rw-r--r-- 1 root root  2840 Sep  2 00:36 sass-3.5.7.gemspec
-rw-r--r-- 1 root root  1625 Sep  2 00:36 sass-listen-4.0.0.gemspec
-rw-r--r-- 1 root root  1273 Sep  2 00:37 sawyer-0.8.1.gemspec
-rw-r--r-- 1 root root  1297 Sep  2 00:36 stud-0.0.23.gemspec
-rw-r--r-- 1 root root  2012 Sep  2 00:37 terminal-table-1.8.0.gemspec
-rw-r--r-- 1 root root  1574 Sep  2 00:37 thread_safe-0.3.6.gemspec
-rw-r--r-- 1 root root  1267 Sep  2 00:37 typhoeus-1.3.0.gemspec
-rw-r--r-- 1 root root  2754 Sep  2 00:37 tzinfo-1.2.5.gemspec
-rw-r--r-- 1 root root  1642 Sep  2 00:37 unicode-display_width-1.4.0.gemspec
```

**Comment by dmalan** [comment]
@kzidane mind taking a stab at this too?

**Comment by kzidane** [comment]
https://github.com/bundler/bundler/issues/6691
https://github.com/cs50/cli/pull/59
